name: 0-geospatial-indexing-fundamentals

services:
  api:
    image: starciacademy/system-design-geospatial-indexing-fundamentals-api:latest
    container_name: 0-geospatial-indexing-fundamentals-api
    ports:
      - "3016:3000"
    environment:
      - PORT=3000
      - H3_RESOLUTION=9
    networks:
      - 0-geospatial-indexing-fundamentals-network

networks:
  0-geospatial-indexing-fundamentals-network:
    name: 0-geospatial-indexing-fundamentals-network
