name: 2-matching-and-dynamic-pricing

services:
  redis:
    image: redis:7-alpine
    container_name: 2-matching-and-dynamic-pricing-redis
    ports:
      - "6397:6379"
    networks:
      - 2-matching-and-dynamic-pricing-network

  api:
    image: starciacademy/system-design-matching-and-dynamic-pricing-api:latest
    container_name: 2-matching-and-dynamic-pricing-api
    ports:
      - "3018:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - GEO_KEY=drivers:live
      - H3_RESOLUTION=9
    depends_on:
      - redis
    networks:
      - 2-matching-and-dynamic-pricing-network

networks:
  2-matching-and-dynamic-pricing-network:
    name: 2-matching-and-dynamic-pricing-network
